name: 2XL
favicon: null
layout_spectrum: 0.40819
typography_spectrum: 0.12807
title: 2XL Online – We help you to excel online
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0069b3'
    - '#00aae8'
    - '#b4d2e9'
    - '#69c9f3'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
