name: 2XL
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7392396507784724
title: Byrå med fokus på digital marknadsföring med smarta och effektiva medielösningar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0069b3'
    - '#00aae8'
    - '#b4d2e9'
    - '#69c9f3'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.6562036238610744
  rhythmicContrast: 0.6159526477567852
purpose: []
