analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#0069b3'
    - '#00aae8'
    - '#b4d2e9'
    - '#69c9f3'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 0.25
  saturation: 0.1875
cta: {}
layout_spectrum: 0.577702
name: 2XL
opengraph: {}
purpose: []
typography_spectrum: 0.528716
